Concatenate

In [1]:
import numpy as np

In [4]:
arr1 = np.array([2,3,4])
arr2 = np.array([3,4,6])


res = np.concatenate([arr1,arr2],axis=0)
print(res)

[2 3 4 3 4 6]


In [7]:
mat1 = np.array([[2,3],
                 [3,4]])

mat2 = np.array([[5,2],
                 [4,8]])

res1 = np.concatenate([mat1,mat2],axis=1)

print(res1)

[[2 3 5 2]
 [3 4 4 8]]


Reshape

In [11]:
arr = np.arange(1,13)
print(arr)

print("Reshaped matrix")
arr.reshape(2,6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped matrix


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Split

In [13]:
matrix = np.random.randint(1,15,size=(4,4))
print(matrix)

[[ 9 14  3 10]
 [ 7 10 12  4]
 [ 9  3 12 11]
 [ 2  7  9 13]]


In [19]:
np.split(matrix,2,axis=1)

[array([[ 9, 14],
        [ 7, 10],
        [ 9,  3],
        [ 2,  7]]),
 array([[ 3, 10],
        [12,  4],
        [12, 11],
        [ 9, 13]])]

In [22]:
np.hsplit(matrix,4)

[array([[9],
        [7],
        [9],
        [2]]),
 array([[14],
        [10],
        [ 3],
        [ 7]]),
 array([[ 3],
        [12],
        [12],
        [ 9]]),
 array([[10],
        [ 4],
        [11],
        [13]])]

In [23]:
matrix

array([[ 9, 14,  3, 10],
       [ 7, 10, 12,  4],
       [ 9,  3, 12, 11],
       [ 2,  7,  9, 13]])

In [24]:
np.vsplit(matrix,2)

[array([[ 9, 14,  3, 10],
        [ 7, 10, 12,  4]]),
 array([[ 9,  3, 12, 11],
        [ 2,  7,  9, 13]])]

stack

In [25]:
mat1

array([[2, 3],
       [3, 4]])

In [26]:
mat2

array([[5, 2],
       [4, 8]])

In [31]:
np.stack([mat1,mat2],axis=0)

array([[[2, 3],
        [3, 4]],

       [[5, 2],
        [4, 8]]])

In [34]:
np.vstack([mat1,mat2])

array([[2, 3],
       [3, 4],
       [5, 2],
       [4, 8]])

In [35]:
np.hstack([mat1,mat2])

array([[2, 3, 5, 2],
       [3, 4, 4, 8]])

In [38]:
matrix

array([[ 9, 14,  3, 10],
       [ 7, 10, 12,  4],
       [ 9,  3, 12, 11],
       [ 2,  7,  9, 13]])

In [37]:
matrix.T

array([[ 9,  7,  9,  2],
       [14, 10,  3,  7],
       [ 3, 12, 12,  9],
       [10,  4, 11, 13]])

copy() vs view()

In [39]:
mat_1 = mat1.copy()

In [50]:
print(mat_1)
print(id(mat1))
print(id(mat_1))

[[2 3]
 [3 4]]
4605763984
4601444944


In [63]:
mat1[0][0] = 9

In [65]:
print(mat_1)

[[2 3]
 [3 4]]


In [60]:
mat_2 = mat2.view()
print(mat_2)

[[3 2]
 [4 8]]


In [61]:

mat2[0][0] = 4
print(mat2)

[[4 2]
 [4 8]]


In [62]:
print(mat_2)

[[4 2]
 [4 8]]
