# Numpy

In [1]:
import time
import numpy as np

In [2]:
#python list
py_lst = list(range(1_000_000))
start = time.time()
sum(py_lst)
lst_time = time.time() - start

#numpy array
np_arr = np.arange(1_000_000)
start = time.time()
np_arr.sum()
arr_time = time.time() - start

print(f"List time: {lst_time*1000.:2f}ms")
print(f"np Array time: {arr_time*1000.:2f}ms")


List time: 2.543926ms
np Array time: 1.028776ms


intallation of numpy

In [ ]:
!pip install numpy

import numpy library

In [6]:
import numpy as np #alias

Creating array in numpy

In [ ]:
# 1 dimension array
lst = [34,56,89,23,90,12]
arr = np.array(lst)
#1 dimension array is the array where you have multiple comma separated scaler values

In [10]:
type(arr)

numpy.ndarray

In [12]:
# 2 Dimension array

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

# 2 dimensional is the array where you have multiple comma seperated 1 dimensional arrays
print(matrix)
print(type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [25]:
# 3 Dimensional array

t_darr = np.array(
    [
        [[23,45],
        [34,67],
        [56,87]],

        [[34,25],
        [78,90],
        [23,12]]

        ]
)
# 3 dimensional array is the array where you have multiple 2 dimensional arrays

print(t_darr)


[[[23 45]
  [34 67]
  [56 87]]

 [[34 25]
  [78 90]
  [23 12]]]


## ndim 

In [14]:
print(arr.ndim)

1


In [15]:
print(matrix.ndim)


2


In [23]:
print(t_darr.ndim)


3


## shape

In [18]:
arr

array([34, 56, 89, 23, 90, 12])

In [17]:
arr.shape

(6,)

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matrix.shape

(3, 3)

In [26]:
t_darr.shape

(2, 3, 2)

## size

In [27]:
arr.size

6

In [28]:
matrix.size

9

In [29]:
t_darr.size

12

## dtype

In [30]:
arr.dtype

dtype('int64')

In [31]:
matrix.dtype

dtype('int64')

## Special array

In [36]:
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [37]:
matrix1 = np.zeros((3,2))
print(matrix1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## arange

In [45]:
arr2 = np.arange(5)
print(arr2)

[0 1 2 3 4]


In [51]:
arr2 = np.arange(2,21,2)
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20]


## linspace

In [58]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [62]:
np.ones((3,4),dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])