In [41]:
lst = [119, 142,  76, 143, 146, 191,  60, 140, 163,  89, 142,  20,  74,
         1, 163, 188, 142, 164, 186, 196,  26, 168,  23,  12,  24,  85,
         8, 142, 180, 115,  87,  28,  80,  -5, 198,  27,  -8, 186,  64,
        -6, 143,  74,  51,   8,  41,  20, 167, 193,  10,  20,   1, 144,
       111,  -3,   8,  37,  31,  -8, 151, 143, 171,  70, 197, 165, 196,
        -2,  70,  18,  26,  -5, 143,  40,  -8,  22,  32,  30,  97,  48,
        78,  47, 102, 173,   2,  28, 153,  68,  55,  90, 128, 175,  24,
        91, 123, 165, 149, 149,   5, 144, 124,   0]

In [1]:
import numpy as np

# Indexing 1d & 2D

In [2]:
arr = np.array([45,67,90,23,13,345,23])

In [4]:
arr[2]

90

In [5]:
matrix = np.array([
    [3,4,2],
    [4,6,2],
    [4,3,7]
])

[
    [00,01,02],
    [10,11,12],
    [20,21,22]
]

In [15]:
matrix[1][1]

6

In [13]:
matrix[1][1]

6

In [14]:
matrix[0][1]

4

# Slicing

In [17]:
arr

array([ 45,  67,  90,  23,  13, 345,  23])

In [21]:
arr[3:7]

array([ 23,  13, 345,  23])

In [22]:
matrix

array([[3, 4, 2],
       [4, 6, 2],
       [4, 3, 7]])

In [31]:
matrix[1:3,1:3]

array([[6, 2],
       [3, 7]])

In [34]:
arr

array([ 45,  67,  90,  23,  13, 345,  23])

In [37]:
arr[4:]

array([ 13, 345,  23])

In [38]:
matrix

array([[3, 4, 2],
       [4, 6, 2],
       [4, 3, 7]])

In [40]:
matrix[1:,1:]

array([[6, 2],
       [3, 7]])

In [42]:
temp = np.array(lst)

# Boolean Filtering

In [45]:
arr

array([ 45,  67,  90,  23,  13, 345,  23])

In [47]:
arr[arr<40]

array([23, 13, 23])

In [51]:
print(temp[temp<=100])

[76 60 89 20 74  1 26 23 12 24 85  8 87 28 80 -5 27 -8 64 -6 74 51  8 41
 20 10 20  1 -3  8 37 31 -8 70 -2 70 18 26 -5 40 -8 22 32 30 97 48 78 47
  2 28 68 55 90 24 91  5  0]


>= 100 and <=1

In [52]:
temp[(temp<=100) & (temp>=1)]

array([76, 60, 89, 20, 74,  1, 26, 23, 12, 24, 85,  8, 87, 28, 80, 27, 64,
       74, 51,  8, 41, 20, 10, 20,  1,  8, 37, 31, 70, 70, 18, 26, 40, 22,
       32, 30, 97, 48, 78, 47,  2, 28, 68, 55, 90, 24, 91,  5])

In [53]:
temp[(temp<=100) | (temp>=1)]

array([119, 142,  76, 143, 146, 191,  60, 140, 163,  89, 142,  20,  74,
         1, 163, 188, 142, 164, 186, 196,  26, 168,  23,  12,  24,  85,
         8, 142, 180, 115,  87,  28,  80,  -5, 198,  27,  -8, 186,  64,
        -6, 143,  74,  51,   8,  41,  20, 167, 193,  10,  20,   1, 144,
       111,  -3,   8,  37,  31,  -8, 151, 143, 171,  70, 197, 165, 196,
        -2,  70,  18,  26,  -5, 143,  40,  -8,  22,  32,  30,  97,  48,
        78,  47, 102, 173,   2,  28, 153,  68,  55,  90, 128, 175,  24,
        91, 123, 165, 149, 149,   5, 144, 124,   0])

# Fancy Indexing

In [54]:
arr

array([ 45,  67,  90,  23,  13, 345,  23])

In [58]:
arr[[0,3,5]]

array([ 45,  23, 345])

In [63]:
arr[[True,False,True,False,True,False,True]]

array([45, 90, 13, 23])

In [67]:
arr>=70

array([False, False,  True, False, False,  True, False])

In [68]:
arr[[False, False,  True, False, False,  True, False]]

array([ 90, 345])

# Modifying values

Squashing

In [72]:
temp[temp<0] = 0

In [77]:
temp[temp>100] = 100

In [79]:
temp[(temp<0) | (temp>100)]

array([], dtype=int64)