In [3]:
import numpy as np

arr = np.array([3,2,5])

# multiply all the elments with 7
res = arr / 7
print(res)

[0.42857143 0.28571429 0.71428571]


peform operations between arrays

In [7]:
arr1 = np.array([34,67,90]) #price
arr2 = np.array([3,5,2]) #quantity

res = arr1 * arr2
print(res)

[102 335 180]


In [8]:
mat1 = np.array([[2,4],[4,5]])
mat2 = np.array([[3,6],[5,7]])

In [9]:
mat1

array([[2, 4],
       [4, 5]])

In [10]:
mat2

array([[3, 6],
       [5, 7]])

In [11]:
mat1 * mat2

array([[ 6, 24],
       [20, 35]])

In [15]:
arr1[arr1 > 40]

array([67, 90])

Brodcasting

In [17]:
arr1 * 2

array([ 68, 134, 180])

In [19]:
arr1 * np.array([2,2,2])

array([ 68, 134, 180])

In [20]:
matrix = np.array([[34,45,56],
                   [43,78,78],
                   [56,67,87]])

print(matrix * 2)

[[ 68  90 112]
 [ 86 156 156]
 [112 134 174]]


row broadcasting

In [23]:
row = np.array([2,4,5])

print(matrix * row)

[[ 68 180 280]
 [ 86 312 390]
 [112 268 435]]


column broadcasting

In [24]:
column = np.array([[2],
                   [3],
                   [4]])

print(matrix + column)

[[36 47 58]
 [46 81 81]
 [60 71 91]]


in row broadcast.. number of columns should be same

and in column broadcast.. number of rows should be same

Vectorization

In [31]:
res = []
for i in [34,67,90]:
    res.append(i*2+5)

res

[73, 139, 185]

In [30]:
arr1

array([34, 67, 90])

In [29]:
arr1 * 2 + 5

array([ 73, 139, 185])

math functions

In [33]:
arr1.sum()

191

In [34]:
arr1.prod()

205020

In [35]:
arr1.cumsum()

array([ 34, 101, 191])

In [36]:
np.power(arr1,2)

array([1156, 4489, 8100])

In [37]:
np.subtract(arr1,arr2)

array([31, 62, 88])

statistical functions

In [39]:
round(arr1.mean(),3)

63.667

In [41]:
np.median(arr1)

67.0

In [42]:
arr1.min()

34

In [43]:
matrix.max()

87

In [44]:
arr1.std()

22.9830855679176

In [45]:
arr1.var()

528.2222222222222

Axis parameter

In [48]:
matrix

array([[34, 45, 56],
       [43, 78, 78],
       [56, 67, 87]])

In [54]:
matrix.mean(axis=0)

array([44.33333333, 63.33333333, 73.66666667])

axix = 1 represents row = 

In [53]:
matrix.sum(axis=1)

array([135, 199, 210])

In [52]:
np.array([34,45,56]).mean()

45.0

Sorting in numpy

In [82]:
arr = np.array([45,34,78,12,67,90,33])

In [68]:
arr

array([12, 33, 34, 45, 67, 78, 90])

In [67]:
arr.sort(kind='quicksort')

In [72]:
matrix.sort(axis=1)

In [73]:
matrix

array([[34, 45, 56],
       [43, 67, 78],
       [56, 78, 87]])

In [75]:
arr[::-1]

array([90, 78, 67, 45, 34, 33, 12])

In [77]:
np.flip(arr)

array([90, 78, 67, 45, 34, 33, 12])

In [78]:
temp = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])

In [80]:
temp.sort(order='y')

In [81]:
temp

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i8')])

In [83]:
arr

array([45, 34, 78, 12, 67, 90, 33])

In [84]:
arr.argsort()

array([3, 6, 1, 0, 4, 2, 5])